<?php if ( $this->pageCount > 1): ?>
    <div class="buttons-row">
        <ul class="buttons">
            <?php if (isset($this->previous)): ?>
                <li class="active"><a href="<?= $this->url(array("pageNum"=>$this->previous))?>">&larr;</a></li>
            <?php endif; ?>
            <?php foreach ($this->pagesInRange as $page): ?>
                <?php if ($page != $this->current): ?>
                    <li class="active"><a href="<?= $this->url(array("pageNum" => $page)) ?>"><?= $page; ?></a></li>
                <?php else: ?>
                    <li class="counter"><?= $page; ?></li>
                <?php endif; ?>
            <?php endforeach; ?>
            <?php if (isset($this->next)): ?>
                <li class="active"><a href="<?= $this->url(array("pageNum"=>$this->next))?>">&rarr;</a></li>
            <?php endif; ?>
        </ul>
    </div>
<?php endif; ?>