<section class="ad">
    <h2 class="top-title"><span>МЫ РЕКОМЕНДУЕМ</span></h2>
    <?php foreach( $this->recommends as $recommend ): ?>
        <?php $recommendContent = $recommend->getContent()->getFields();?>
        <div class="recommend">
            <?php $url = $recommendContent['url']->getFieldText(); ?>
            <?php if (empty($url)): ?>
                <?php echo $recommendContent['content']->getFieldText() ?>
                <div class="box">
                    <img src="<?php echo $recommend->getPhoto1()->getPath('180:150') ?>" alt="<?php echo $recommendContent['content']->getFieldText() ?>" width="180" height="150" />
                </div>
            <?php else: ?>
                <?php echo $recommendContent['content']->getFieldText() ?>
                <div class="box">
                    <a href="<?php echo $url; ?>">
                        <img src="<?php echo $recommend->getPhoto1()->getPath('180:150') ?>" alt="GET MOVIES, TV SHOVS &amp; GAMES DELIVERED" width="180" height="150" />
                    </a>
                </div>
                <span class="row"><a href="<?php echo $url; ?>" class="link"><?php echo $recommendContent['content']->getFieldText() ?></a></span>
            <?php endif; ?>
        </div>
    <?php endforeach;?>
</section>