<? $this->headScript()->captureStart() ?>
    function addView(id){
        $.ajax({
            type: "POST",
            url: '/galleryowner/addview',
            data: {"id":id},
            success: function(result) {}
        });
    }
<? $this->headScript()->captureEnd() ?>
<div class="top-container">
    <article class="top-visuals">
        <article class="main-info">
            <?php foreach($this->publicList->data as $public): ?>
                <?php $publicContent = $public->getContent()->getFields();
                $publicContentText = strip_tags($publicContent['content']->getFieldText()); ?>
                <section class="main-visual">
                    <div class="mask main-mask">
                        <!--noindex-->
                        <a href="<?php echo $public->getRoute()->getUrl();?>" rel="nofollow">
                            <img src="<?php echo $public->getPhoto1()->getPath('529:396')?>" alt="<?php echo $publicContent['contentName']->getFieldText();?>" width="529" height="396" />
                        </a>
                        <!--/noindex-->
                    </div>
                </section>
                <section class="text-block">
                    <h3>
                        <a href="<?php echo $public->getRoute()->getUrl();?>"><?php echo $publicContent['contentName']->getFieldText();?></a>
                    </h3>
                    <!--noindex-->
                    <p><?php echo trim(mb_substr($publicContentText, 0, 250, 'utf8')); ?>...
                        <br/>
                        <a href="<?php echo $public->getRoute()->getUrl();?>" rel="nofollow" class="more">Читать &raquo;</a>
                    </p>
                    <!--/noindex-->
                </section>
                <?php break;?>
            <?php endforeach; ?>
        </article>
        <aside class="info-column">
            <?php echo $this->ShowCategorys();?>
        </aside>
    </article>
    <aside class="news-column" style="text-align: center;">
        <div class="heading">
            <h2>А также</h2>
        </div>
        <section class="profile-box">
            <script type="text/javascript"><!--
            google_ad_client = "ca-pub-3861532892125732";
            /* wifi_left_long */
            google_ad_slot = "3607121498";
            google_ad_width = 160;
            google_ad_height = 600;
            //-->
            </script>
            <script type="text/javascript"
                    src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
            </script>
        </section>
    </aside>
</div>
<section class="gallery-container">
    <h3 class="top-title"><span>Последние публикации</span></h3>
    <div class="gallery2">
        <div class="mask">
            <ul>
                <?php $i=0;?>
                <?php foreach($this->publicList->data as $public): ?>
                    <?php if($i==0){$i++;continue;}?>
                    <?php $publicContent = $public->getContent()->getFields();
                    $publicContentText = strip_tags($publicContent['content']->getFieldText()); ?>
                    <li>
                        <div class="visual">
                            <!--noindex-->
                            <a href="<?php echo $public->getRoute()->getUrl();?>" rel="nofollow">
                                <img src="<?php echo $public->getPhoto1()->getPath('180:99')?>" alt="<?php echo $publicContent['contentName']->getFieldText();?>" width="180" height="99" />
                            </a>
                            <!--/noindex-->
                        </div>
                        <h3>
                            <a href="<?php echo $public->getRoute()->getUrl();?>"><?php echo $publicContent['contentName']->getFieldText();?></a>
                        </h3>
                        <!--noindex-->
                        <p><?php echo trim(mb_substr($publicContentText, 0, 75, 'utf8')); ?>...
                            <br/>
                            <a href="<?php echo $public->getRoute()->getUrl();?>" rel="nofollow" class="more">Читать &raquo;</a>
                        </p>
                        <!--/noindex-->
                    </li>
                    <?php $i++;?>
                <?php endforeach; ?>
            </ul>
        </div>
        <a href="#" class="prev">&lt;</a>
        <a href="#" class="next">&gt;</a>
    </div>
</section>
<div id="main">
    <article id="content">
        <section class="posts-block">
            <ul class="posts">
                <li>
                    <div class="text-box">
                        <h3>Главное о wi-fi роутерах</h3>
                        <?php echo $this->contentPage['content']->getFieldText();?>
                    </div>
                </li>
            </ul>
        </section>
    </article>
    <aside id="sidebar">
        <div class="block">
            <h3 class="top-title"><span>И ЕЩЕ</span></h3>
            <div class="ad">
                <div class="box">
                    <script type="text/javascript"><!--
                    google_ad_client = "ca-pub-3861532892125732";
                    /* wifi_right_linog */
                    google_ad_slot = "0666393957";
                    google_ad_width = 160;
                    google_ad_height = 600;
                    //-->
                    </script>
                    <script type="text/javascript"
                            src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
                    </script>
                </div>
            </div>
        </div>
    </aside>
</div>