<!--<html>
	<head>
		<title>Application error</title>
		<? // =$this->headMeta()?>
	</head>
  	<body>
		<h2><?php // echo $this->message ?></h2>
  		<?php // if (isset($this->exception)): ?>
	  		<h3>Exception information:</h3>
	  		<p><b>Message:</b> <?php // echo $this->exception->getMessage() ?></p>
	
	  		<h3>Stack trace:</h3>
	  		<pre><?php // echo $this->exception->getTraceAsString() ?></pre>
	
	  		<h3>Request Parameters:</h3>
	  		<pre><?php // echo var_export($this->request->getParams(), true) ?></pre>
  		<?php // endif ?>
  	</body>
</html>-->
<!DOCTYPE html>
<html lang="ru">
    <head>
        <title>404 - ошибка</title>
        <meta name="description" content="404 - ошибка<" />
        <meta name="keywords" content="404  ошибка<" /> 

        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <meta name="google-site-verification" content="_ZougryiBOI1qTeThy2b4DaJjxwfSfxufiKMZ3CR0YE" />

        
        <!-- styles -->
        <link rel="stylesheet" href="/static/default/css/reset.css" type="text/css" media="screen" />
        <link rel="stylesheet" href="/static/default/css/fonts.css" type="text/css" media="screen" />
        <link rel="stylesheet" href="/static/default/css/jquery.tipsy.css" type="text/css" media="screen" />
        <link rel="stylesheet" href="/static/default/css/jquery.fancybox-1.3.4.css" type="text/css" media="screen" />
        <link rel="stylesheet" href="/static/default/css/main.css" type="text/css" media="screen" />
        <!--[if IE]><link rel="stylesheet" href="/static/default/css/ie.css" type="text/css" media="screen" /><![endif]-->
        <!--[if IE 7]><link rel="stylesheet" href="/static/default/css/ie7.css" type="text/css" media="screen" /><![endif]-->
        <!-- scripts -->
        <script type="text/javascript" src="/static/default/js/jquery-1.7.2.min.js"></script>
        <script type="text/javascript" src="/static/default/js/jquery.tipsy.js"></script>
        <script type="text/javascript" src="/static/default/js/jquery.fancybox-1.3.4.pack.js"></script>
        <script type="text/javascript" src="https://maps.google.com/maps/api/js?sensor=false"></script>
        <script type="text/javascript" src="/static/default/js/main.js"></script>
        <!--[if lt IE 9]><script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script><![endif]-->
        
        <script type="text/javascript">
          var _gaq = _gaq || [];
          _gaq.push(['_setAccount', 'UA-11535685-10']);
          _gaq.push(['_trackPageview']);

          (function() {
            var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
            ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
          })();
        </script>
        
    </head>
    <body>
        <div class="cite">
            <div><div class="quotes"></div>Фраза дня</div>
            <p><?php echo $this->siteSetings->getUrl1()?></p>
        </div>
        <header style="background-image: url(<?php echo $this->siteSetings->getPhoto1()->getPath('1040:162')?>)">
            <hgroup>
                <h1><a href="/"><?php echo strip_tags($this->blocks['name_first']['contentName']->getFieldText())?></a></h1>
                <h6><a href="/"><?php echo strip_tags($this->blocks['my_blog']['contentName']->getFieldText())?></a></h6>
            </hgroup>
        </header>
        <?php echo $this->partial('blocks/menu.phtml', array('menu' => $this->menu, 'blocks'=>$this->blocks)) ?>
        <div id="content">
                <div class="col-680">
                    <section>
                        <header>
                            <h4 class="orange-flower">404 - ошибка</h4>
                        </header>
                        <p>Вы ппали на страницу которой уже давно не существует. <br/> Ищите дальше :)</p>
                    </section>
                </div>
            <div class="clear"></div>
        </div>
        <?php echo $this->partial('blocks/footer.phtml', array('blocks'=>$this->blocks)) ?>
    </body>
</html>