<!--<html>
	<head>
		<title>Application error</title>
		<? // =$this->headMeta()?>
	</head>
  	<body>
		<h2><?php // echo $this->message ?></h2>
  		<?php // if (isset($this->exception)): ?>
	  		<h3>Exception information:</h3>
	  		<p><b>Message:</b> <?php // echo $this->exception->getMessage() ?></p>
	
	  		<h3>Stack trace:</h3>
	  		<pre><?php // echo $this->exception->getTraceAsString() ?></pre>
	
	  		<h3>Request Parameters:</h3>
	  		<pre><?php // echo var_export($this->request->getParams(), true) ?></pre>
  		<?php // endif ?>
  	</body>
</html>-->
<!DOCTYPE html>
<html lang="ru">
<head>
    <title>404 - ошибка</title>
    <meta name="keywords" content="404 - ошибка" />
    <meta name="description" content="404 - ошибка" />
    <?php echo $this->headMeta() ?>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="google-site-verification" content="_ZougryiBOI1qTeThy2b4DaJjxwfSfxufiKMZ3CR0YE" />

    <?php if( isset ($this->headCanonical) ) echo $this->headCanonical; ?>

    <link media="all" rel="stylesheet" href="/static/default/css/all.css">
    <script type="text/javascript" src="/static/default/js/jquery-1.7.2.min.js"></script>
    <script type="text/javascript" src="/static/default/js/main.js"></script>

    <!--[if lt IE 9]>
    <link rel="stylesheet" type="text/css" href="/static/default/css/ie.css" media="screen"/>
    <![endif]-->

    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,600,400italic,600italic,700italic,700' rel='stylesheet' type='text/css'>

    <script type="text/javascript">
        var _gaq = _gaq || [];
        _gaq.push(['_setAccount', 'UA-11535685-10']);
        _gaq.push(['_trackPageview']);

        (function() {
            var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
            ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
        })();
    </script>

    <?php echo $this->headScript() ?>
</head>
<body>
<div class="page">
    <?php echo $this->partial('blocks/menu.phtml', array('menu' => $this->menu, 'blocks'=>$this->blocks,'siteSetings'=>$this->siteSetings)) ?>
    <div id="wrapper">
        <div class="wrapper-holder">
            <div id="main">
                <article id="content">
                    <section class="posts-block">
                        <h1>404 -ошибка</h1>

                        <div class="text-box">

                        </div>
                    </section>
                </article>
                <aside id="sidebar">
                    <?php echo $this->ShowCategorys();?>
                    <br/>
                    <div class="block">
                        <h3 class="top-title"><span></span></h3>
                        <div class="ad">
                            <div class="box">
                                <script type="text/javascript"><!--
                                    google_ad_client = "ca-pub-3861532892125732";
                                    /* wifi_right_linog */
                                    google_ad_slot = "0666393957";
                                    google_ad_width = 160;
                                    google_ad_height = 600;
                                    //-->
                                </script>
                                <script type="text/javascript"
                                        src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
                                </script>
                            </div>
                        </div>
                    </div>
                </aside>
            </div>
        </div>
    </div>
    <?php echo $this->partial('blocks/footer.phtml', array('blocks'=>$this->blocks,'siteSetings'=>$this->siteSetings)) ?>
</div>
</body>
</html>
