<? $this->headScript()->captureStart() ?>
<? $this->headScript()->captureEnd() ?>
<div id="main">
    <article id="content">
        <section class="posts-block">
            <ul class="posts">
                <?php foreach($this->publicList->data as $k=>$public): ?>
                    <?php $publicContent = $public->getContent()->getFields();
                    $publicContentText = strip_tags($publicContent['content']->getFieldText()); ?>
                    <li>
                        <!--noindex-->
                        <div class="visual">
                            <a href="<?php echo $public->getRoute()->getUrl();?>" rel="nofollow">
                                <img src="<?php echo $public->getPhoto1()->getPath('180:125')?>" alt="<?php echo $publicContent['contentName']->getFieldText();?>" width="180" height="125" />
                            </a>
                        </div>
                        <!--/noindex-->
                        <div class="text-box">
                            <h3><a href="<?php echo $public->getRoute()->getUrl();?>"><?php echo $publicContent['contentName']->getFieldText();?></a></h3>
                            <!--noindex-->
                            <p><?php echo trim(mb_substr($publicContentText, 0, 250, 'utf8')); ?>...<br/>
                                <a href="<?php echo $public->getRoute()->getUrl();?>" rel="nofollow" class="more">Читать &raquo;</a>
                            </p>
                            <!--/noindex-->
                        </div>
                    </li>
                    <? if ($k == 1 || $k == 4): ?>
                        <li>
                            <div class="text-box" style="text-align: center;">
                                <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
                                <!-- wifi категории -->
                                <ins class="adsbygoogle"
                                     style="display:inline-block;width:580px;height:400px"
                                     data-ad-client="ca-pub-3861532892125732"
                                     data-ad-slot="3266082092"></ins>
                                <script>
                                    (adsbygoogle = window.adsbygoogle || []).push({});
                                </script>
                            </div>
                        </li>
                    <? endif; ?>
                <?php endforeach; ?>
            </ul>
            <?php echo $this->paginationControl($this->publicList->paginator, 'Sliding', 'block/paginator.phtml')?>
        </section>
        <p><?php echo isset($this->categoryContent['content'])?$this->categoryContent['content']->getFieldText():$this->contentPage['content']->getFieldText();?></p>
    </article>
    <aside id="sidebar">
        <?php echo $this->ShowCategorys();?>
        <br/>
        <div class="block">
            <h3 class="top-title"></h3>
            <div class="ad">
                <div class="box">
                    <script type="text/javascript"><!--
                    google_ad_client = "ca-pub-3861532892125732";
                    /* wifi_right_linog */
                    google_ad_slot = "0666393957";
                    google_ad_width = 160;
                    google_ad_height = 600;
                    //-->
                    </script>
                    <script type="text/javascript"
                            src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
                    </script>
                </div>
            </div>
        </div>
    </aside>
</div>