<? $this->headScript()->captureStart() ?>
<? $this->headScript()->captureEnd() ?>
<div id="main">
    <article id="content">
        <section class="posts-block">
            <ul class="posts">
                <li>
                    <h3><?php echo $this->contentPage['contentName']->getFieldText();?></h3>
                    <div class="text-box">
                        <?php echo $this->contentPage['content']->getFieldText();?>
                        <br/>
                        <ul class="terms">
                            <li><time datetime="<?php echo date('Y-m-d', $this->product->getPageEditDate());?>"><?php echo Application_Model_Kernel_Date_Manager::formatDate($this->product->getPageEditDate(), Application_Model_Kernel_Date_Manager::TYPE_USER_VIEW)?></time></li>
                            <li><?php echo $this->categoryText;?></li>
                        </ul>
                    </div>
                </li>
            </ul>
        </section>
        <section style="margin-top: -70px;">
            <?php // echo $this->ShowComments( $this->product->getIdProduct(), Application_Model_Kernel_Comment::TYPE_PUBLIC );?>
            <div id="disqus_thread"></div>
            <script type="text/javascript">
                /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
                var disqus_shortname = 'wifi-hard'; // required: replace example with your forum shortname

                /* * * DON'T EDIT BELOW THIS LINE * * */
                (function() {
                    var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
                    dsq.src = 'http://' + disqus_shortname + '.disqus.com/embed.js';
                    (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
                })();
            </script>
            <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
            <a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
        </section>
        <section class="stories-container" style="margin-top: 10px;">
            <h3 class="top-title">
                <span>Другие публикации</span>
            </h3>
            <ul class="stories">
                <?php foreach($this->publicList->data as $public): ?>
                    <?php $publicContent = $public->getContent()->getFields();
                    $publicContentText = strip_tags($publicContent['content']->getFieldText()); ?>
                    <li>
                        <figure class="visual">
                            <a href="<?php echo $public->getRoute()->getUrl();?>">
                                <img src="<?php echo $public->getPhoto1()->getPath('219:130')?>" alt="<?php echo $publicContent['contentName']->getFieldText();?>" width="219" height="130" />
                            </a>
                            <figcaption>
                                <a href="<?php echo $public->getRoute()->getUrl();?>"><?php echo $publicContent['contentName']->getFieldText();?></a>
                            </figcaption>
                        </figure>
                    </li>
                <?php endforeach; ?>
            </ul>
        </section>
    </article>
    <aside id="sidebar">
        <?php echo $this->ShowCategorys();?>
        <?php echo $this->ShowRecomend();?>
        <br/>
        <div class="block">
            <h3 class="top-title"><span>И ЕЩЕ</span></h3>
            <div class="ad">
                <div class="box">
                    <script type="text/javascript"><!--
                    google_ad_client = "ca-pub-3861532892125732";
                    /* wifi_right_linog */
                    google_ad_slot = "0666393957";
                    google_ad_width = 160;
                    google_ad_height = 600;
                    //-->
                    </script>
                    <script type="text/javascript"
                            src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
                    </script>
                </div>
            </div>
        </div>
    </aside>
</div>