<? $this->headScript()->captureStart() ?>
<? $this->headScript()->captureEnd() ?>
<style>
    .posts-block h1 {
        text-transform: uppercase;
        font-style: italic;
        font-size: 20px;
        line-height: 22px;
        margin: 0 0 8px;
    }
    blockquote p {
        background: #e3e3e3;
        border-left: 4px solid #D6D6D6;
        border-right: 4px solid #D6D6D6;
        border-radius: 14px;
        margin-bottom: 24px;
        padding: 24px;
        font-style: italic;
    }
</style>
<? $categoryMain = $this->product->getFirstCategory();?>
<? $categoryMainContent = $categoryMain->getContent()->getFields();?>
<div id="main">
    <article id="content">
        <section class="posts-block">
            <h1><?php echo $this->contentPage['contentName']->getFieldText();?></h1>
            <div class="text-box"  style="text-align: center; position: relative; height: 15px">
                <div style="position: absolute; top: 0px; left:0px;">
                    <ul class="terms">
                        <li>
                            <a href="/">Wi-fi роутеры</a>
                        </li>
                        <li>
                            <a href="<?=$this->url(array('sort'=>0,'pageNum'=>1,'idCategory'=>$categoryMain->getid()),'public-page-16')?>"><?=$categoryMainContent['contentName']->getFieldText();?></a>
                        </li>
                        <li>...</li>
                    </ul>
                </div>
                <!--noindex-->
                <div style="position: absolute; top: 0px; right:0px;">
                    <a href="#disqus_thread" rel="nofollow">отзывы</a>
                </div>
                <!--/noindex-->
            </div>
            <div class="text-box"  style="text-align: center;">
                <img src="<?php echo $this->product->getPhoto1()->getPath('529:396')?>" alt="" width="529" height="396" />
            </div>
            <div class="text-box">
                <?php
                $arrAdvert = array ();
                // 1 - номер после какого абзаца и <<<EOD1 ... EOD1; - содержимое что будет выводится
                $arrAdvert[2] = '
                    <div style="text-align: center;">
                        <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
                        <!-- wifi в статье -->
                        <ins class="adsbygoogle"
                             style="display:inline-block;width:580px;height:400px"
                             data-ad-client="ca-pub-3861532892125732"
                             data-ad-slot="4302163290"></ins>
                        <script>
                        (adsbygoogle = window.adsbygoogle || []).push({});
                        </script>
                    </div>
                    ';
                $arrAdvert['last'] = '
                    <div style="text-align: center;">
                       <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
                            <!-- wifi в конце статьи -->
                            <ins class="adsbygoogle"
                                 style="display:inline-block;width:580px;height:400px"
                                 data-ad-client="ca-pub-3861532892125732"
                                 data-ad-slot="5778896497"></ins>
                            <script>
                            (adsbygoogle = window.adsbygoogle || []).push({});
                        </script>
                    </div>
                    ';

                $contentPost = $this->contentPage['content']->getFieldText();
                if (substr_count($contentPost, '<p') > 2) {
                    $contents = explode("</p>", $contentPost);
                    foreach ($contents as $k => $content) {
                        echo $content;
                        if (isset($arrAdvert[$k + 1]))
                            echo $arrAdvert[$k + 1];
                        if (isset($arrAdvert['prelast'])) {
                            if ((count($contents) - 3) == $k) {
                                echo $arrAdvert['prelast'];
                            }
                        }
                        if (isset($arrAdvert['last'])) {
                            if (count($contents) == ($k + 1)) {
                                echo $arrAdvert['last'];
                            }
                        }
                        echo "";
                    }
                } else {
                    echo $contentPost;
                } ?>
            </div>
        </section>
        <section style="margin-top: -30px;">
            <div id="disqus_thread"></div>
            <script type="text/javascript">
                /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
                var disqus_shortname = 'wifi-hard'; // required: replace example with your forum shortname

                /* * * DON'T EDIT BELOW THIS LINE * * */
                (function() {
                    var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
                    dsq.src = 'http://' + disqus_shortname + '.disqus.com/embed.js';
                    (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
                })();
            </script>
            <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
        </section>
        <section class="stories-container" style="margin-top: 10px;">
            <h3 class="top-title">
                <span>Другие публикации</span>
            </h3>
            <ul class="stories">
                <?php foreach($this->publicList->data as $public): ?>
                    <?php $publicContent = $public->getContent()->getFields();
                    $publicContentText = strip_tags($publicContent['content']->getFieldText()); ?>
                    <li>
                        <figure class="visual">
                            <a href="<?php echo $public->getRoute()->getUrl();?>">
                                <img src="<?php echo $public->getPhoto1()->getPath('219:130')?>" alt="<?php echo $publicContent['contentName']->getFieldText();?>" width="219" height="130" />
                            </a>
                            <figcaption>
                                <a href="<?php echo $public->getRoute()->getUrl();?>"><?php echo $publicContent['contentName']->getFieldText();?></a>
                            </figcaption>
                        </figure>
                    </li>
                <?php endforeach; ?>
            </ul>
        </section>
    </article>
    <aside id="sidebar">
        <?php echo $this->ShowCategorys();?>
        <br/>
        <div class="block">
            <h3 class="top-title"><span></span></h3>
            <div class="ad">
                <div class="box">
                    <script type="text/javascript"><!--
                    google_ad_client = "ca-pub-3861532892125732";
                    /* wifi_right_linog */
                    google_ad_slot = "0666393957";
                    google_ad_width = 160;
                    google_ad_height = 600;
                    //-->
                    </script>
                    <script type="text/javascript"
                            src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
                    </script>
                </div>
            </div>
        </div>
    </aside>
</div>