<? $this->headScript()->captureStart() ?>
<? $this->headScript()->captureEnd() ?>
<section>
    <div class="col-680">
        <section>

        </section>
    </div>
</section>
<div id="main">
    <article id="content">
        <section class="posts-block">
            <header>
                <h4 class="orange-flower"><?php echo $this->contentPage['contentName']->getFieldText()?></h4>
            </header>
            <?php echo $this->contentPage['content']->getFieldText()?>
            <br/>
            <a href="http://plus.google.com/118393108679325493018/about" title="Google+" class="gp" rel="me">Мой профиль в Google+</a>
        </section>
    </article>
    <aside id="sidebar">
        <?php echo $this->ShowCategorys();?>
        <br/>
        <div class="block">
            <h3 class="top-title"></h3>
            <div class="ad">
                <div class="box">
                    <script type="text/javascript"><!--
                        google_ad_client = "ca-pub-3861532892125732";
                        /* wifi_right_linog */
                        google_ad_slot = "0666393957";
                        google_ad_width = 160;
                        google_ad_height = 600;
                        //-->
                    </script>
                    <script type="text/javascript"
                            src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
                    </script>
                </div>
            </div>
        </div>
    </aside>
</div>
